// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateCompany(arg1:main.CompanyInput):Promise<main.Company>;

export function CreateTheme(arg1:main.ThemeInput):Promise<main.Theme>;

export function CreateThesis(arg1:main.ThesisInput):Promise<main.Thesis>;

export function CreateThesisReview(arg1:main.ThesisReviewInput):Promise<main.ThesisReview>;

export function DBPath():Promise<string>;

export function DashboardStats():Promise<main.DashboardStats>;

export function GetAISettings():Promise<main.AISettings>;

export function GetAttachmentPreview(arg1:number):Promise<main.AttachmentPreview>;

export function GlobalSearch(arg1:string):Promise<Array<main.GlobalSearchItem>>;

export function ImportAIParseResult(arg1:main.AIImportInput):Promise<main.AIImportResult>;

export function LinkCompanyTheme(arg1:main.CompanyThemeInput):Promise<main.CompanyThemeView>;

export function ListAttachments(arg1:main.AttachmentListInput):Promise<Array<main.Attachment>>;

export function ListCompanies(arg1:string):Promise<Array<main.Company>>;

export function ListCompanyThemes(arg1:number,arg2:number,arg3:boolean):Promise<Array<main.CompanyThemeView>>;

export function ListThemeChangeLogs(arg1:number):Promise<Array<main.ThemeChangeLog>>;

export function ListThemes(arg1:string):Promise<Array<main.Theme>>;

export function ListTheses(arg1:number):Promise<Array<main.Thesis>>;

export function ListThesisReviews(arg1:number):Promise<Array<main.ThesisReview>>;

export function ParseThemeContent(arg1:main.AIParseInput):Promise<main.AIParseResult>;

export function SaveAISettings(arg1:main.AISettings):Promise<main.AISettings>;

export function SaveAttachments(arg1:main.AttachmentInput):Promise<Array<main.Attachment>>;

export function UpdateCompany(arg1:main.CompanyUpdateInput):Promise<main.Company>;

export function UpdateThemeMeta(arg1:main.ThemeMetaUpdateInput):Promise<main.Theme>;

export function ValidateAIImport(arg1:main.AIImportValidationInput):Promise<main.AIImportValidation>;
