// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCompany(arg1) {
  return window['go']['main']['App']['CreateCompany'](arg1);
}

export function CreateTheme(arg1) {
  return window['go']['main']['App']['CreateTheme'](arg1);
}

export function CreateThesis(arg1) {
  return window['go']['main']['App']['CreateThesis'](arg1);
}

export function CreateThesisReview(arg1) {
  return window['go']['main']['App']['CreateThesisReview'](arg1);
}

export function DBPath() {
  return window['go']['main']['App']['DBPath']();
}

export function DashboardStats() {
  return window['go']['main']['App']['DashboardStats']();
}

export function GetAISettings() {
  return window['go']['main']['App']['GetAISettings']();
}

export function GetAttachmentPreview(arg1) {
  return window['go']['main']['App']['GetAttachmentPreview'](arg1);
}

export function GlobalSearch(arg1) {
  return window['go']['main']['App']['GlobalSearch'](arg1);
}

export function ImportAIParseResult(arg1) {
  return window['go']['main']['App']['ImportAIParseResult'](arg1);
}

export function LinkCompanyTheme(arg1) {
  return window['go']['main']['App']['LinkCompanyTheme'](arg1);
}

export function ListAttachments(arg1) {
  return window['go']['main']['App']['ListAttachments'](arg1);
}

export function ListCompanies(arg1) {
  return window['go']['main']['App']['ListCompanies'](arg1);
}

export function ListCompanyThemes(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListCompanyThemes'](arg1, arg2, arg3);
}

export function ListThemeChangeLogs(arg1) {
  return window['go']['main']['App']['ListThemeChangeLogs'](arg1);
}

export function ListThemes(arg1) {
  return window['go']['main']['App']['ListThemes'](arg1);
}

export function ListTheses(arg1) {
  return window['go']['main']['App']['ListTheses'](arg1);
}

export function ListThesisReviews(arg1) {
  return window['go']['main']['App']['ListThesisReviews'](arg1);
}

export function ParseThemeContent(arg1) {
  return window['go']['main']['App']['ParseThemeContent'](arg1);
}

export function SaveAISettings(arg1) {
  return window['go']['main']['App']['SaveAISettings'](arg1);
}

export function SaveAttachments(arg1) {
  return window['go']['main']['App']['SaveAttachments'](arg1);
}

export function UpdateCompany(arg1) {
  return window['go']['main']['App']['UpdateCompany'](arg1);
}

export function UpdateThemeMeta(arg1) {
  return window['go']['main']['App']['UpdateThemeMeta'](arg1);
}

export function ValidateAIImport(arg1) {
  return window['go']['main']['App']['ValidateAIImport'](arg1);
}
